apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{gitops.name}}
  namespace: {{gitops.namespace}}
  labels:
    app.kubernetes.io/name: {{gitops.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{gitops.name}}
  template:
    metadata:
      labels:
        app: {{gitops.name}}
        version: v-{{gitops.version}}
        deploy: d-{{gitops.deploy}}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '{{gitops.port}}'
    spec:
      containers:
        - name: app
          image: {{gitops.imageName}}:{{gitops.imageTag}}
          imagePullPolicy: Always

          args:
          - --zone
          - {{gitops.config.zone}}
          - --region
          - {{gitops.config.region}}

          ports:
            - name: http
              containerPort: {{gitops.port}}
              protocol: TCP
