#!/bin/bash

# name: clean
# short: Remove the apps from the local k3d cluster

# change to this directory
#cd "$(dirname "${BASH_SOURCE[0]}")" || exit

kubectl delete ns myapp --ignore-not-found=true --wait=false
kubectl delete ns logging --ignore-not-found=true --wait=false
kubectl delete ns monitoring --ignore-not-found=true --wait=false
kubectl delete pod jumpbox --ignore-not-found=true --wait=false
