#!/bin/bash

# name: deploy
# short: Deploy the apps to the local k3d cluster

# change to this directory
#cd "$(dirname "${BASH_SOURCE[0]}")" || exit

# validate directories
if [ ! -d "$REPO_BASE/myapp/deploy" ]; then echo "deploy directory not found"; exit 1; fi

# create namespace
kubectl apply -f "$REPO_BASE/myapp/deploy"
kubectl apply -f "$REPO_BASE/myapp/deploy/bootstrap"
kubectl apply -R -f "$REPO_BASE/myapp/deploy/bootstrap"

kic deploy app &
kic deploy webv

sleep 5
kic pods

echo ""
echo "run 'kic pods' until the pods are running"
