#!/bin/bash

#name: all
#short: Run all status checks on the local cluster

echo "Checking app"
"$(dirname "${BASH_SOURCE[0]}")/app"

echo "Checking WebV"
"$(dirname "${BASH_SOURCE[0]}")/webv"

echo "Checking Grafana"
"$(dirname "${BASH_SOURCE[0]}")/grafana"

echo "Checking Prometheus"
"$(dirname "${BASH_SOURCE[0]}")/prometheus"
