#!/bin/bash

#name: webapi
#short: Create a new dotnet WebAPI

date > newapp.log

if [ "$AKDC_REPO" = "" ]
then
    echo "Please export AKDC_REPO"
    exit 1
fi

if [ "$AKDC_BRANCH" = "" ]
then
    echo "Please export AKDC_BRANCH"
    exit 1
fi

# update the app name if a valid name
export APP_NAME=$1
export APP_LOWER=$(echo "$APP_NAME" | tr '[:upper:]' '[:lower:]')

if [[ "$APP_NAME" =~ ^[A-Z][A-Za-z][A-Za-z][A-Za-z][A-Za-z]+$ ]]
then
    if [ -d "$APP_LOWER" ]
    then
        echo "Directory $APP_LOWER already exists"
        exit 1
    fi

    git pull
    git clone https://github.com/retaildevcrews/dotnet-webapi-template "$APP_LOWER"
    cd "$APP_LOWER" || exit

    rm -rf .devcontainer
    rm -rf .git
    rm -rf .github
    rm -f .gitignore
    rm -f LICENSE
    rm -f curl.sh

    mv src/csapp.csproj "src/$APP_LOWER.csproj"

    sed -i "s/{{branch}}/$AKDC_BRANCH/g" ci-cd/deploy.yaml
    sed -i "s@{{repo}}@$AKDC_REPO@g" ci-cd/deploy.yaml

    find . -name '*' -type f -exec sed -i "s/CSApp/$APP_NAME/g" {} \;
    find . -name '*' -type f -exec sed -i "s/csapp/$APP_LOWER/g" {} \;

    # todo - uncomment this
    # mkdir -p ../.github/workflows
    # mv ci-cd/*.yaml ../.github/workflows
    # rm -rf ci-cd

    # deploy bootstrap
    kubectl apply -f deploy
    kubectl apply -f deploy/bootstrap
    kubectl apply -R -f deploy/bootstrap

    dotnet restore src &

    # deploy webv
    kic deploy webv &

    # build and deploy the app
    kic deploy app

    # echo ""
    # echo "waiting for bootstrap to complete"
    # echo ""
    # kubectl wait pod -l app=prometheus-server -n monitoring --for condition=ready --timeout 30s

    # echo ""
    # echo "waiting for app to start"
    # echo "press ctl-c to abort the load and integration tests"
    # echo ""

    # kubectl wait pod -l app="$APP_LOWER" -n "$APP_LOWER" --for condition=ready --timeout 30s
    # kic pods

    # echo ""
    # echo ""
    # echo "running load test"
    # kic test load &

    # give the load test time to start
    # sleep 5
    # kic test integration > /dev/null 2>&1

    # echo ""
    # echo ""
    # echo "running integration test"
    # kic test integration
    # echo ""
    # echo "$APP_NAME created, built, deployed, tested"
    # echo ""
    date >> ../newapp.log
else
    echo "Invalid App Name $1"
fi
