#!/bin/bash

#name: webapi
#short: Create a new dotnet WebAPI

# update the app name if a valid name
export APP_NAME=$1
export APP_LOWER=$(echo "$APP_NAME" | tr '[:upper:]' '[:lower:]')

if [[ "$APP_NAME" =~ ^[A-Z][A-Za-z][A-Za-z][A-Za-z][A-Za-z]+$ ]]
then
    if [ -d "$APP_LOWER" ]
    then
        echo "Directory $APP_LOWER already exists"
        exit 1
    fi

    git pull
    git clone https://github.com/retaildevcrews/dotnet-webapi-template "$APP_LOWER"
    cd "$APP_LOWER" || exit

    kubectl delete -R -f deploy --wait=false --ignore-not-found=true

    rm -rf .devcontainer
    rm -rf .git
    rm -rf .github
    rm -f .gitignore
    rm -f LICENSE
    rm -f curl.sh

    mv src/myapp.csproj "src/$APP_LOWER.csproj"

    sed -i "s/myapp/$APP_LOWER/g" .kic/commands/app/build
    sed -i "s/myapp/$APP_LOWER/g" .kic/commands/app/deploy
    sed -i "s/cd \"\$REPO_BASE\" || exit//g" .kic/commands/app/build
    sed -i "s~deploy/apps~apps~g" autogitops/autogitops.json
    sed -i "s/myapp/$APP_LOWER/g" Dockerfile
    find . -name '*.*' -type f -exec sed -i "s/MyApp/$APP_NAME/g" {} \;
    find . -name '*.*' -type f -exec sed -i "s/myapp/$APP_LOWER/g" {} \;
    dotnet restore src

    rm -rf .kic

    kic build app
    kic build webv

    kubectl wait ns monitoring --for condition=delete --timeout=30s --ignore-not-found=true
    kubectl wait ns logging --for condition=delete --timeout=30s --ignore-not-found=true

    kubectl apply -f deploy/bootstrap
    kubectl apply -R -f deploy/bootstrap

    kubectl wait pod -l app=myapp -n myapp --for condition=ready --timeout 30s

    echo ""
    echo "running integration test"
    kic test integration
    echo ""

    kic pods

else
    echo "Invalid App Name $1"
fi
