name: MyApp CD

on:
  push:
    branches:
      - main

    paths:
    - 'myapp/autogitops/**'
    - '.github/workflows/deploy.yaml'

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Docker pull
      run: |
        docker pull ghcr.io/retaildevcrews/autogitops:0.4.1

    - name: GitOps Deploy
      run: |
        docker run \
        --name ago \
        --rm \
        -v $(pwd)/myapp:/ago \
        ghcr.io/retaildevcrews/autogitops:0.4.1 \
        -r retaildevcrews/bartr-app \
        -b bartr-demo-fleet \
        -p ${{ secrets.GHCR_PAT }}
